language: node_js
node_js:
  - "10.16.3"
script:
  - firebase deploy
install:
  - npm install
  - npm install -g firebase-tools
  - npm run build
after_success:
  - firebase deploy --project arise-team-strapi --token $FIREBASE_TOKEN
